apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer # distribute the load accros pods

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      targetPort: 8161
    - name: endpoint
      port: 61616
      targetPort: 61616
  selector:
    app: queue
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-position-tracker
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: position-tracker
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-api-gateway
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: api-gateway
  type: ClusterIP